name = "dumplin-api"
main = "src/index.ts"
compatibility_date = "2024-11-28"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "0a88f51d028445308d64c950ca30079c"
localConnectionString =

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "1900ababe57f45c4979896fbac40e5ac"

[observability]
[observability.logs]
enabled = true
